In [7]:
import numpy as np

In [21]:
def softmax(X):
    exp_num = np.exp(-X)

    print('exp(XX^T) = ')
    # print(np.round(exp_num, 2))
    print(exp_num)
    print('')

    exp_sum = np.sum(exp_num, axis=1)
    
    print('sum(exp(XX^T)) = ')
    # print(np.round(exp_sum, 2))
    print(exp_sum)
    print('')
    
    return np.nan_to_num(exp_num / exp_sum, nan=0)

def rand_ints(size):
    return np.random.randint(0,9, size)

X = np.array([
    np.random.randint(1, 100, 3),
    np.array([3,5,7]),               # Should be similar wrt row 4
    np.array([3,5,7]),               # Should be similar wrt row 1
])

print('Input X = ')
print(X)
print('')

print('XX^T = ')
print(X @ X.T)
print('')


atten_weights = softmax(X @ X.T)

print('Attention Weights Softmax[XX^T] = ')
print(np.round(atten_weights, 2))

print('')
print('Self Attention, Y =')
print(np.round(atten_weights @ X, 2))

Input X = 
[[52 48 16]
 [ 3  5  7]
 [ 3  5  7]]

XX^T = 
[[5264  508  508]
 [ 508   83   83]
 [ 508   83   83]]

exp(XX^T) = 
[[0.00000000e+000 2.39002912e-221 2.39002912e-221]
 [2.39002912e-221 8.98582594e-037 8.98582594e-037]
 [2.39002912e-221 8.98582594e-037 8.98582594e-037]]

sum(exp(XX^T)) = 
[4.78005825e-221 1.79716519e-036 1.79716519e-036]

Attention Weights Softmax[XX^T] = 
[[0.  0.  0. ]
 [0.5 0.5 0.5]
 [0.5 0.5 0.5]]

Self Attention, Y =
[[ 0.  0.  0.]
 [29. 29. 15.]
 [29. 29. 15.]]


In [22]:
X = np.array([
    np.arange(1,6),
    np.arange(1,6),               # Should be similar wrt row 4
    np.random.randint(0, 100, 5),
    np.random.randint(50, 1000, 5),
    np.random.randint(80, 500, 5),
])

print('X = ')
print(X)
print('')



print('XX^T = ')
print(X @ X.T)
print('')


print('Attention Weights Softmax[XX^T] = ')
atten_weights = softmax(X @ X.T)
print(np.round(atten_weights, 2))

print('')
print('Self Attention, Y =')
print(np.round(atten_weights @ X, 2))

Input X = 
[[  1   2   3   4   5]
 [  1   2   3   4   5]
 [ 42  48  28  57  67]
 [905 108 273 378 796]
 [354 226 251 492 247]]

XX^T = 
[[     55      55     785    7432    4762]
 [     55      55     785    7432    4762]
 [    785     785   12590  125716   77337]
 [   7432    7432  125716 1681718  795889]
 [   4762    4762   77337  795889  542466]]

Attention Weights Softmax[XX^T] = 
exp(XX^T) = 
[[1.29958143e-24 1.29958143e-24 0.00000000e+00 0.00000000e+00
  0.00000000e+00]
 [1.29958143e-24 1.29958143e-24 0.00000000e+00 0.00000000e+00
  0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00
  0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00
  0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00
  0.00000000e+00]]

sum(exp(XX^T)) = 
[2.59916285e-24 2.59916285e-24 0.00000000e+00 0.00000000e+00
 0.00000000e+00]

[[0.5 0.5 0.  0.  0. ]
 [0.5 0.5 0.  0.  0. ]
 [0.  0.  0.  0.  0. ]
 [0.  0.  0.  0.  0. ]
 [0.  0.

/var/folders/1j/chhd52wn0z97rq9skbstg0_00000gn/T/ipykernel_2932/1564840644.py:16: RuntimeWarning: invalid value encountered in divide
  return np.nan_to_num(exp_num / exp_sum, nan=0)
