In [77]:
import numpy as np
import jax.numpy as jnp
import jax

In [87]:
def softmax(matrix):
    # Subtract the max for numerical stability
    shift_matrix = matrix - np.max(matrix, axis=1, keepdims=True)
    exp_matrix = np.exp(shift_matrix)
    sum_exp = np.sum(exp_matrix, axis=1, keepdims=True)
    softmax_matrix = exp_matrix / sum_exp
    return np.round(softmax_matrix, 10)

In [95]:
X = np.array([
    np.array([3,5,7]),               # Should be similar wrt row 4
    np.random.randint(1, 10, 3),
    np.array([3,5,7]),               # Should be similar wrt row 1
])

print(jax.nn.softmax(X @ X.T))
print(softmax(X @ X.T))
# print(jax)

[[5.0000000e-01 1.7212387e-14 5.0000000e-01]
 [4.5395809e-05 9.9990916e-01 4.5395809e-05]
 [5.0000000e-01 1.7212387e-14 5.0000000e-01]]
[[5.00000000e-01 0.00000000e+00 5.00000000e-01]
 [4.53958000e-05 9.99909208e-01 4.53958000e-05]
 [5.00000000e-01 0.00000000e+00 5.00000000e-01]]


In [94]:
softmax(np.eye(3)) * X

array([[ 1.72835065,  1.05970779,  1.4835909 ],
       [11.020961  , 25.34914293, 11.020961  ],
       [ 0.63582467,  1.05970779,  4.03281819]])

In [108]:

def rand_ints(size):
    return np.random.randint(0,9, size)

X = np.array([
    np.random.randint(1, 10, 3),
    np.array([3,5,7]),               # Should be similar wrt row 4
    np.array([3,5,7]),               # Should be similar wrt row 1
])

print('Input X = ')
print(X)
print('')

print('X^T = ')
print(X.T)
print('')

print('XX^T = ')
print(X @ X.T)
print('')


atten_weights = softmax(X @ X.T)

print('Attention Weights Softmax[XX^T] = ')
print(np.round(atten_weights, 2))

print('')
print('Self Attention, Y =')
print(np.round(atten_weights @ X, 2))

Input X = 
[[7 8 4]
 [3 5 7]
 [3 5 7]]

X^T = 
[[7 3 3]
 [8 5 5]
 [4 7 7]]

XX^T = 
[[129  89  89]
 [ 89  83  83]
 [ 89  83  83]]

Attention Weights Softmax[XX^T] = 
[[1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]]

Self Attention, Y =
[[7.   8.   4.  ]
 [6.98 7.99 4.01]
 [6.98 7.99 4.01]]


In [64]:
X = np.array([
    np.arange(1,6),
    np.arange(1,6),               # Should be similar wrt row 4
    np.random.randint(0, 100, 5),
    np.random.randint(50, 1000, 5),
    np.random.randint(80, 500, 5),
])
# X = np.array([
#     np.arange(1,6),
#     np.arange(1,6),               # Should be similar wrt row 4
#     np.random.randint(0, 10, 5),
#     np.random.randint(10, 20, 5),
#     np.random.randint(10, 30, 5),
# ])

print('X = ')
print(X)
print('')

print('X^T = ')
print(X.T)
print('')


print('XX^T = ')
print(X @ X.T)
print('')


print('Attention Weights Softmax[XX^T] = ')
# atten_weights = softmax(X @ X.T)
atten_weights = jax.nn.softmax(X @ X.T).numpy()
print(np.round(atten_weights, 2))

print('')
print('Self Attention, Y =')
print(np.round(atten_weights @ X, 2))

X = 
[[  1   2   3   4   5]
 [  1   2   3   4   5]
 [ 35  65   1  42  99]
 [910  70 894 638 916]
 [101 116 488 125 192]]

X^T = 
[[  1   1  35 910 101]
 [  2   2  65  70 116]
 [  3   3   1 894 488]
 [  4   4  42 638 125]
 [  5   5  99 916 192]]

XX^T = 
[[     55      55     831   10864    3257]
 [     55      55     831   10864    3257]
 [    831     831   17016  154774   35821]
 [  10864   10864  154774 2878336  791924]
 [   3257    3257   35821  791924  314290]]

Attention Weights Softmax[XX^T] = 


AttributeError: 'ArrayImpl' object has no attribute 'tonumpy'