In [2]:
import numpy as np

In [3]:
def softmax(X):
    exp_num = np.exp(-X)
    exp_sum = np.sum(exp_num, axis=1)
    return np.nan_to_num(exp_num / exp_sum, nan=0)

def rand_ints(size):
    return np.random.randint(0,9, size)

X = np.array([
    np.random.randint(1, 100, 3),
    np.array([3,5,7]),               # Should be similar wrt row 4
    np.array([3,5,7]),               # Should be similar wrt row 1
])

print('Input X = ')
print(X)
print('')
print('Attention Weights Softmax[XX^T] = ')
atten_weights = softmax(X @ X.T)
print(np.round(atten_weights, 2))

print('')
print('Self Attention, Y =')
print(np.round(atten_weights @ X, 2))

Input X = 
[[ 2 99 42]
 [ 3  5  7]
 [ 3  5  7]]

Attention Weights Softmax[XX^T] = 
[[0.  0.  0. ]
 [0.  0.5 0.5]
 [0.  0.5 0.5]]

Self Attention, Y =
[[0. 0. 0.]
 [3. 5. 7.]
 [3. 5. 7.]]


/var/folders/1j/chhd52wn0z97rq9skbstg0_00000gn/T/ipykernel_2932/2953581310.py:4: RuntimeWarning: invalid value encountered in divide
  return np.nan_to_num(exp_num / exp_sum, nan=0)


In [5]:
X = np.array([
    np.arange(1,6),
    np.arange(1,6),               # Should be similar wrt row 4
    np.random.randint(0, 100, 5),
    np.random.randint(50, 1000, 5),
    np.random.randint(80, 500, 5),
])

print('Input X = ')
print(X)
print('')
print('Attention Weights Softmax[XX^T] = ')
atten_weights = softmax(X @ X.T)
print(np.round(atten_weights, 2))

print('')
print('Self Attention, Y =')
print(np.round(atten_weights @ X, 2))

Input X = 
[[  1   2   3   4   5]
 [  1   2   3   4   5]
 [ 58   4  24  48  68]
 [404 922  60 544 756]
 [415 385 132  84 359]]

Attention Weights Softmax[XX^T] = 
[[0.5 0.5 0.5 0.  0. ]
 [0.5 0.5 0.5 0.  0. ]
 [0.  0.  0.  0.  0. ]
 [0.  0.  0.  0.  0. ]
 [0.  0.  0.  0.  0. ]]

Self Attention, Y =
[[30.  4. 15. 28. 39.]
 [30.  4. 15. 28. 39.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]]


/var/folders/1j/chhd52wn0z97rq9skbstg0_00000gn/T/ipykernel_2932/2953581310.py:4: RuntimeWarning: invalid value encountered in divide
  return np.nan_to_num(exp_num / exp_sum, nan=0)
